//Nutzen Sie dieses Template als Grundlage für die Spezifikation *einzelner* Use-Cases. Diese lassen sich dann per Include in das Use-Case Model Dokument einbinden (siehe Beispiel dort).

== Use-Case 03: GPS-Tracks auf der Karte anzeigen 

=== Kurzbeschreibung
//<Kurze Beschreibung des Use Case>
Darstellung der aktuellen Position sowie der bisher aufgenommenen Routen auf der Karte.

=== Kurzbeschreibung der Akteure

==== Benutzer 
Benutzer möchte seine Position, die bisher aufgenommene Route oder eine bereits abgeschlossenen GPS-Track auf der Karte sehen.

=== Vorbedingungen
//Vorbedingungen müssen erfüllt, damit der Use Case beginnen kann, z.B. Benutzer ist angemeldet, Warenkorb ist nicht leer...

* Benutzer hat die App geöffnet.
* Der App wurde die GPS- und Dateispeicher-Berechtigung erteilt.
* Benutzer verfügt über eine funktionierende Internet-, und GPS-Verbindung.

=== Standardablauf (Basic Flow)
//Der Standardablauf definiert die Schritte für den Erfolgsfall ("Happy Path")

Der Use Case beginnt, wenn Benutzer die App öffnet

. Eine Karte wird angezeigt und die aktuelle Position des Benutzer wird erkennbar
. Der Use Case ist abgeschlossen.

=== Alternative Abläufe
//Nutzen Sie alternative Abläufe für Fehlerfälle, Ausnahmen und Erweiterungen zum Standardablauf

//==== Optionale Fortsetzung 
//Wenn der Nutzer nach Abschluss des  Standartablaufes den Button "aufnehmen" betätigt, dann

//. wird Use Case 01 gestartet
//. Die bisher aufgezeichnete Route wird auf der Karte abgebildet

==== Optionale Fortsetzung
Wenn der Benutzer keine Internetverbindung mehr hat, kann er keine neuen Abschnitte der Karte mehr laden und dies
wird dem Benutzer mit einem Pop-up mitgeteilt.

==== Optionale Fortsetzung 
Wenn der Benutzer nach Abschluss des Standardablaufes den "Aufnehemen" Button betätigt, so wird (UC01) gestartet
und die aufgenommene Route wird in Form eines Pfades auf der Karte angezeigt.

==== Optionale Fortsetzung 
Wenn der Benutzer nach Abschluss des Standardablaufes einen abgeschlossenen GPS-Track auswählt (UC02)
und anschließend im Optionsmenu den Punkt "GPS-Track Anzeigen" auswählt, dann wird der ausgewählte GPS-Track angezeigt.

=== Wesentliche Szenarios
//Szenarios sind konkrete Instanzen eines Use Case, d.h. mit einem konkreten Akteur und einem konkreten Durchlauf der o.g. Flows. Szenarios können als Vorstufe für die Entwicklung von Flows und/oder zu deren Validierung verwendet werden.
* SC1: Der Benutzer will wissen wo er ist oder ob die Messung der App mit der Realität übereinstimmt.
* SC2: Benutzer will bisher aufgenommene Strecke sehen um festzustellen ob diese seinen Anforderungen entspricht.
* SC3: Benutzer will bereits beendete Strecke betrachten um festzustellen ob manuelle Bearbeitungen notwendig sind (UC03).

=== Nachbedingungen
//Nachbedingungen beschreiben das Ergebnis des Use Case, z.B. einen bestimmten Systemzustand.
Der Benutzer sieht die gewünschten Inhalte auf der Karte.

//==== <Nachbedingung 1>
//
//=== Besondere Anforderungen
//Besondere Anforderungen können sich auf nicht-funktionale Anforderungen wie z.B. einzuhaltende Standards, Qualitätsanforderungen oder Anforderungen an die Benutzeroberfläche beziehen.
//
//==== <Besondere Anforderung 1>
