= Iteration Plan 03: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Meilensteine

[cols="1,1"]
|===
|*Meilenstein*
|*Datum*
|Beginn der Iteration
|16.01.2022
|Meeting mit Coach
|18.01.2022
|Meeting mit TS
|21.01.2022
|Ende der Iteration
|23.01.2022
|===


== Wesentliche Ziele
. Systemweite Anforderungen Ausarbeiten
. Vision vervollständigen
. Risikoliste updaten
. Erste Funktionalitäten der App/Software programmieren (Karte auf Homescreen anzeigen, Positionsermittlung per GPS)
. Iterationsplan erstellen, Projektplan vervollständigen und ins Repo holen

== Aufgabenzuordnung
https://github.com/RaphaelNeubert/I5_GPS_Tracks/projects/2

== Bewertungskriterien
* Die Systemweiten Anforderungen, die Vision und die Risikoliste werden beim Zusammentreffen aller Gruppenmitglieder für gut ausgearbeitet erklärt
* Die Karte kann in der App auf dem Homescreen angezeigt werden
* Die Positionsermittlung per GPS in der App funktioniert 


== Assessment


[cols="1,1"]
|===
| Assessment Ziel
| Ganze Iteration
| Assessment Datum
| 23.01.2022
| Teilnehmer
| Alle Gruppenmitglieder außer Richard
| Projektstatus
| grün
|===


    • Fast alle für die Iteration festgelegten Ziele wurden so weit erfüllt.
    • Alle Aufgabe, welche geplant waren, wurden bis zum Ende der Iteration bearbeitet.
    • Jedoch wurden die Iterationspläne und der Projektplan noch nicht ins Repo geholt, weshalb diese Aufgabe in die nächste Iteration verschoben wird. 
    • Während der Iteration hat es ein paar Änderungen innerhalb der Aufgaben gegeben und Ergänzungen gegeben. 
    • Dies betrifft zum einen das Architektur Notebook, welches nun schon zusätzlich begonnen worden ist und dann weiter fortgeführt wird.
    • Des Weiteren kam es zu kleinen Änderungen und Anpassungen durch die Tipps des Coaches und des Themenstellers.
    • Diese folgenden Anpassungen wurden dabei in der Iteration noch zusätzlich vorgenommen: Der Butten für das Menü der App und der für die Aufnahme bekommen ein anderes Symbol, und es wird ein weiterer Button hinzugefügt. 
    • Zudem wird noch einmal über die Wörter Track und Tracks geschaut, um diese in allen Dokumenten einheitlich zu schreiben.
    • Die Beurteilung für die Bewertungskriterien fällt sehr positiv aus.
    • Die Systemweiten Anforderungen, die Vision und die Risikoliste wurden beim Zusammentreffen aller Gruppenmitglieder für gut ausgearbeitet erklärt und somit als abgabebereit erklärt.
    • Die App hat die ersten Funktionstests bestanden, dabei kann Karte kann in der App auf dem Homescreen angezeigt werden und die Positionsermittlung per GPS funktioniert mit sogar hoher Genauigkeit.
    • Da die Iterationen zu Ende hin sehr voll werden wurde sich dazu entschieden die Iteration 3 in zwei Iterationen Aufzuteilen, Wodurch alle sich in der Icebox und Assigned befindlichen Aufgaben in Iteration 4 verschoben werden und nicht zu Iteration 3 zählen.
