= Projektplan: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der folgende Projektplan ist das Fundament unseres Projektes. Er bündelt alle wichtigen Informationen und Pläne, welche für eine erfolgreiche Projektführung notwendig sind. Zudem werden weitere Elemente wie das Team und die jeweiligen Rollen, Management Techniken und Vorgehen bei der Arbeitsweise, Meilensteine und Ziele und Dokumente für die Entwicklung und den Erkenntniszuwachs betrachtet. Für eine klare Struktur orientieren wir uns in diesem Projekt am Vorgehensmodell: Open Unified Process. Dabei wir das Projekt in vier Phasen unterteilt. In SE I gilt es die Phasen INCEPTIOND und ELABORATION zu bestreiten und in SE II dann CONSTRUCTION UND TRANSITION. 
Dieses Dokument wird fortlaufen ergänzt und überarbeitet.


== Projektorganisation
Das Projektteam besteht aus 8 Studenten der HTW-Dresden aus unterschieldeichen Fachbereichen.
|===
|Anton Peschel | Projektleitung
|Felix Reuß | Analyst, Unterstützung Projektleitung
|Ludwig Schönthier | Analyst, Test
|Richard Michel | Any Role
|Raphael Neubert | Developer, Entwurf, Deployment Engineer, stellvertretende Projektleitung
|Alex Schechtel | Developer, Tester, Any Role
|Tom Nicolai | Developer, Tester
|Quang Duy Pham | Tester, Entwurf
|===
Anton Peschel und Felix Reuß sind beides Wirtschaftsingenieure im fünften Semester, wobei die anderen Gruppenmitglieder alle der Fakultät Informatik angehören und da in verschiedenen Fachbereichen und Fachsemestern studieren.
Beim Wechsel von SE I zu SE II wird Raphael Neubert die Leitung des Projekts übernehmen, da die Wirtschaftsingenieure nur SE I durchlaufen und deshalb in der zweiten Phase nicht mehr am Projekt teilnehmen.
Die Aufgaben- und Rollenverteilung im Projekt ist sehr offen gestaltet. Jeder hat zwar seine zugeordneten Rollen und damit Aufgaben, jedoch hat jeder die Freiheit und auch wenn notwendig, die Verpflichtung, in anderen Bereichen mitzuarbeiten und Gruppenmitglieder zu unterstützen. Somit wollen wir sichern, dass niemand im Leerlauf ist und zeitweise nichts zu tun hat, sondern immer Workload für alle verfügbar ist und auch bearbeitet wird. 
Für die Kommunikation im Team Nutzen wir den Channel ELEMENT. In dieser Anwendung findet unsere komplette interne Kommunikation statt. Hierbei gibt es drei Räume für verschiedene Themen, um uns gut und übersichtlich zu organisieren. Im Raum General geht es um allgemeine projektbezogenen Fragen und Themen. Alle Gruppenmitglieder sind in diesem Raum vertreten, damit jeder auch schriftlich an Diskussionen außerhalb von Meetings teilnehmen kann. Der Raum Links/Meetings ist wie der Name schon sagt für wichtige Dokumente und Links erstellt wurden, damit jeder immer einen guten Überblick, über alle wichtigen stattfindenden Meetings hat. In diesem Raum finden auch alle Gruppenmeetings statt. Des Weiteren werden alle Links zu den BBB-Räumen, in welchen wir uns mit unserem Themensteller und Coach treffen, bereitgestellt. Der dritte Raum trägt den Namen Programming-related. In diesem Raum geht es hauptsächlich um alles was mit dem Part Programmieren, Entwicklung und Test zu tun hat. Kleinere Meetings von den Entwicklern finden in diesem Raum statt. Private Kommunikation findet zwischen den Gruppenmitgliedern in einzelnen, nur für die jeweils beteiligten Personen in Chats statt. Ein weiterer Channel ist WhatsApp, jedoch wird dieser nur sehr selten für dringliche Kommunikation genutzt. Die externe Kommunikation mit dem Themensteller und Coach findet via E-Mail statt und die jeweiligen Meetings über die von den Professoren bereitgestellten BBB-Räume. Der Projektleiter (Anton Peschel für SE I und Raphael Neubert für SE II) ist dabei für die externe Kommunikation zuständig und gibt danach die erhaltenen Informationen an die Gruppenmitglieder weiter. 

== Praktiken und Bewertung
Dieses Projekt steht unter keiner direkten Management Technik, welche sich kontinuierlich durch das Projekt zieht. Dies ist jedoch gewollt. Alle Gruppenmitglieder unter der Führung des Projektleiters stehen in einem sehr engen Kontakt. Durch wöchentlich mindestens 2 oder mehr Meetings gibt es eine konstante „Überwachung“ über jeden Arbeitsfortschritt. Man könnte dies auch als Iteratives Arbeiten bezeichnen. Dabei ist der Projektleiter die Treibende Kraft für Hauptmeetings, bei welchen das weitere Vorgehen geplant wird und im Optimalfall alle Gruppenmitglieder anwesend sein sollten. Jedoch besitzt der Projektleiter keine alleinige Entscheidungsgewalt. Er geht auf jeden Vorschlag der Gruppenmitglieder ein und am Ende wird zusammen im Konsens entschieden. Das heißt es gibt keine hierarchische Struktur in unserem Projekt. Nur in Ausnahmenfällen bestimmt der Projektleiter aktiv, wo es lang geht. In allen anderen Fällen geht es um gutes Teamwork und jeder ist gleichwertig. Nachdem immer am Ende oder Anfang einer Woche in einem großen Team Meeting alle auf den gleichen Stand gebracht wurden, wird das weitere Vorgehen bis zum nächsten Meeting zusammen geplant und Aufgaben verteilt. Die Erfüllung der Aufgaben erfolgt individuell oder in kleinen Gruppen. Beim Vorstellen der Aufgaben in Zwischenmeetings werden dann noch, wenn notwendig, Änderungen vorgenommen. Somit hat jeder einen Überblick über alle erledigten Aufgaben und kann auch an diesen in der Nachbearbeitung im Beisein der Gruppe Veränderungsvorschläge anbringen. Durch diese Art zu arbeiten, mit viel Eigenverantwortung, aber auch Teamwork entsteht ein sehr Transparentes Arbeitsverhältnis auf Augenhöhe. Des Weiteren wird eine detaillierte Dokumentation über jede Aufgabe und Kleinigkeit am Anfang des Projekts überflüssig, da durch mehrere Meetings pro Woche und eine kontinuierliche Aufgabenverteilung, Bearbeitung und Besprechung jeder durchgängig informiert ist und weiß was zu tun ist. Bei längeren Arbeitsphasen werden weiterhin wöchentlich Meetings stattfinden. Zusätzlich dazu werden aber alle zu erledigenden Aufgaben vorher niedergeschrieben und dann in eigen Verantwortung bzw. nur teilweise vorher zugeteilt, da das arbeiten jedes einzelnen, je nach Aufgabe, unterschiedlich schnell von statten geht. Dadurch kann der Fortschritt des Projekts und der einzelnen Bestandteile gut überblickt werden. Zudem kann durch wöchentliche Meetings eine gewisse Flexibilität erreicht werden, da man nicht an lange Arbeitsphasen mit wenig Kontakt zu anderen gebunden ist, sondern wichtige Entscheidungen oder Probleme sehr schnell und mithilfe der gruppe gelöst bzw. getroffen werden.  
Als Strategie für die Entwicklung unserer Software haben wir uns für ein iteratives Arbeiten entschieden. Im Fokus dabei standen besonders häufige Teammeetings, während der verschiedenen Phasen, um immer wieder einzelne Schritte zu wiederholen und kleine Änderungen und Anpassungen vorzunehmen. 
Für die Strukturierung der externen Meeting mit unserem Coach und Themen Steller haben wir geplant, dass die Meetings wöchentlich und immer im Wechsel stattfinden, damit die jeweiligen Tipps und Ergänzungen schon direkt vor dem nächsten zusammentreffen umgesetzt werden können.
Weitere Praktiken die wir anweden, sind neben dem Iterative Development, technische Methoden welche im Open Unified Process empfohlen werden. Dies betrifft vorallem die Shared Vision, Use Case Driven Development in welchem ein Use-Case-Model und die System-Wide-Requirements ausgearbeittet werden und Evolutionary Architecture mit dem Architecture Notbook, welches die Architektur schrittweise verfeinert und überwacht.


== Meilensteine und Ziele
Aufgrund der anfänglich mangelhaften Dokumentation finden sich alle wichtigen Daten und Meetings und deren Ergebnisse in unserer Meeting Dokumentation unter folgendem Link.
Zusammengefasst kann man jedoch festhalten. 
Phase 1 war eine große Iteration. In wöchentlichen Meetings wurden Aufgaben besprochen, geplant und verglichen. Alle Ergebnisse wurden in den jeweiligen Meeting Protokollen festgehalten. 

[%header, cols="1,3a,2"]
|===
| Iteration
| Primary objectives 
| Scheduled start or milestone

| I1
a|
* Team kennenlernen und Rollenverteilung
* Projekt organisieren
* Themensteller kennenlernen und Anforderungen festlegen/besprechen
* Use-Cases erstellen und ausarbeiten
* Risikoliste erstellen
* auf Zwischenpräsentation hinarbeiten
| 
20.11.2021 – 21.12.2021 +
 LCO Meilenstein

| I2
a|
* Ausarbeitung von Vision übernehmen
* Ersten Objektentwurf erstellen (Wireframes)
* Use-Cases überarbeiten und neuen hinzufügen
* Erste Entwicklung Leere App erstellen und ins GitHub pushen
* Use-Case Diagramme erstellen
| 09.01.2022-16.01.2022

| I3
a|
* ITERATIONSPLAN 01
* Systemweite Anforderungen Ausarbeiten
* Vision vervollständigen
* Risikoliste updaten
* Erste Funktionalitäten der App/Software programmieren (Karte auf Homescreen anzeigen, Positionsermittlung per GPS)
* Iterationsplan erstellen, Projektplan vervollständigen 
| 16.01.2022-23.01.2022

| I4
a|
* ITERATIONSPLAN 02
* Architektur-Notebook fertigstellen
* Prototyp für Vorstellung bereitmachen
* Domainmodell erstellen
* Glossar erstellen
* Alle Beleg-Dokumente abgabefertig machen
* Korrekturlesen
| 23.01.2022-30.01.2022 +
LCA Meilenstein
|===


== Deployment
Die Projektergebnisse, in unserem Fall die Android-App, wird unserem Auftraggeber in Form einer APK übergeben, desweitern wird der Sourcecode der App, sowie des Servers auf GitHub bereitgestellt.


== Erkenntnisse (Lessons learned)
Rückblickend kann man für SE I folgendes festhalten. Die Dokumentation des Projektes bis zur Vorlesungsfreien Zeit über Neujahr war nicht ausreichend. Jedes Gruppenmitglied war zwar durch die mehreren wöchentlichen Meetings auf dem neusten Stand und wusste was alle so machen, jedoch konnte man nur sehr während eines Arbeitsprozesses feststellen, wer genau jetzt was macht. Dies führte zwar zu keinen Problemen, da die Anzahl an aufgaben noch sehr überschaubar war, jedoch entsprach es nicht den Projektanforderungen. Die Dokumentation änderte sich dann mit dem Start nach dem Jahreswechsel. Nun wurden für jede einzelne Aufgabe Issues erstellt, welche sich jeder zuweisen konnte und somit war zu jedem Zeitpunkt übersichtlich festgehalten, welches Gruppenmitglied, woran arbeitet. Dies stellte sich als sehr vorteilhaft heraus, da somit die zunehmende Komplexität der Aufgaben nun besser dargestellt werden konnte. Für die Bearbeitung bestimmter Aufgaben, hat sich im Laufe des Projektes herausgestellt, dass sich diese deutlich schneller, effektiver und besser in kleinen Gruppen erarbeiten lassen. So worden zum Beispiel die Wireframes und das Domainenmodell von jeweils drei Personen zusammen erstellt.  Für die Kommunikation wurde während des Projekts ein weiterer Raum in Element erstellt, da die zunehmende Fülle von Informationen unseren Gruppenchats unübersichtlich gemacht hat. Deshalb haben wir alle wichtigen Informationen, Dokumente und Links nun separat geteilt, um dieses von den generellen Diskussionen und Gesprächen zu trennen. Zur Zusammenarbeit im Team kann man nur hauptsächlich nur positives Festhalten. Teamwork und eigenständiges Arbeiten standen in einem sehr guten Verhältnis und die Informatiker wurden von Raphael gut geführt. Alles war sehr harmonisch und wird denke mal auch so in SE II fortgeführt werden. Jedoch gab es eine Person welche sich aus verschiedenen persönlichen/privaten Gründen sehr vom Projekt zurückgenommen hat. Für SE I hat dies das Projekt nicht stark beeinflusst, da alle Aufgaben von dem Rest der Gruppe gut bewältigt worden sind. Jedoch ist es unverantwortlich und nicht im Sinne des Projekts die Arbeitsleistung einer Person kompensieren zu müssen. Für SE I haben wir ein Auge zugedrückt, aber für SE II muss sich daran dringend was ändern. Auf Kontaktversuche vom Projektleiter wurde nicht reagiert und auch in Meetings war die Person nur sehr selten bis nie anwesend. Für die nächste Phase des Projektes, wenn die Wirtschaftsingenieure weg sind und nur noch sechs Informatiker sich der Aufgabe annehmen, muss sich jedoch was ändern. Die Person muss aktiv kontaktiert werden und sich einem persönlichen Gespräch mit der Gruppe stellen um ein Weiteres Vorgehen mit dieser Situation zu Planen. Sollte dies zu keinem Ergebnis führen, muss der Coach über ein weiteres Vorgehen entscheiden. Jedoch wird angestrebt dieses Problem erst einmal intern zu klären. 
Zudem kann man abschließend sagen, dass das iterative Arbeiten und Planen sehr sinnvoll ist und verbunden mit mehreren wöchentlichen Meetings auch sehr zeiteffektiv ist. 


